# Generated by Django 3.2.21 on 2023-09-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published video', 'verbose_name_plural': 'Published videos'},
        ),
    ]
