# Generated by Django 3.2.21 on 2023-09-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAllProxy',
            fields=[
            ],
            options={
                'verbose_name': 'All video',
                'verbose_name_plural': 'All videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
