# Generated by Django 3.2.21 on 2023-09-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_videoallproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProxy',
        ),
        migrations.CreateModel(
            name='VideoPublishedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published video',
                'verbose_name_plural': 'Published videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
